# Generated by Django 5.2.1 on 2026-05-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя покупателя')),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, help_text='Email для подтверждения заказа', max_length=254, null=True, verbose_name='Email')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('delivery_method', models.CharField(blank=True, help_text='courier, pickup, post, cdek', max_length=50, null=True, verbose_name='Способ доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма товаров')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Код купона')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая сумма')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные при доставке'), ('online', 'Онлайн оплата')], default='card', max_length=50, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='new', max_length=30, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='Название товара')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за шт')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказа',
            },
        ),
    ]
