# Generated by Django 5.2.1 on 2026-05-11 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandNormalizeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=255, unique=True)),
                ('normalized_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryNormalizeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=255, unique=True)),
                ('normalized_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_type', models.CharField(choices=[('csv', 'CSV/XLSX structured'), ('dirty_excel', 'Dirty Excel')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supplier_imports/')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'Обработка'), ('completed', 'Готово'), ('failed', 'Ошибка')], default='new', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('created_products', models.IntegerField(default=0)),
                ('updated_products', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.TextField(blank=True, null=True)),
                ('raw_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_price', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_stock', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_category', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_description', models.TextField(blank=True, null=True)),
                ('raw_image', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('success', 'Успех'), ('updated', 'Обновлено'), ('error', 'Ошибка')], default='new', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='importer.supplierimportsession')),
            ],
        ),
    ]
