# Generated by Django 5.2.1 on 2026-06-06 17:57

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_price_and_more'),
        ('importer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='Excel-файл')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Выполняется'), ('completed', 'Завершён'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('log', models.TextField(blank=True, default='', verbose_name='Лог выполнения')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Успешно')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='С ошибками')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто запустил')),
            ],
            options={
                'verbose_name': 'Задача импорта',
                'verbose_name_plural': 'Задачи импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название профиля')),
                ('field_mapping', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Пример: {"sku": "Артикул", "name": "Наименование", "price": "Цена"}', verbose_name='Маппинг полей')),
                ('default_values', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Пример: {"category__name": "Сантехника", "is_active": true}', verbose_name='Значения по умолчанию')),
                ('skip_header', models.BooleanField(default=True, verbose_name='Пропустить первую строку')),
                ('sheet_name', models.CharField(blank=True, help_text='Оставьте пустым для первого листа', max_length=100, verbose_name='Имя листа')),
                ('update_existing', models.BooleanField(default=True, help_text='Если товар с таким SKU уже есть – обновить его данные', verbose_name='Обновлять существующие товары')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('default_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='Бренд по умолчанию')),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория по умолчанию')),
            ],
            options={
                'verbose_name': 'Профиль импорта',
                'verbose_name_plural': 'Профили импорта',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='BrandNormalizeRule',
        ),
        migrations.DeleteModel(
            name='CategoryNormalizeRule',
        ),
        migrations.RemoveField(
            model_name='supplierimportsession',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplierimportrow',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplierimportrow',
            name='session',
        ),
        migrations.AddField(
            model_name='importjob',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='importer.importprofile', verbose_name='Профиль импорта'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierImportRow',
        ),
        migrations.DeleteModel(
            name='SupplierImportSession',
        ),
    ]
