# Generated by Django 5.2.1 on 2026-05-18 08:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Уникальный код для применения', max_length=50, unique=True, verbose_name='Код купона')),
                ('name', models.CharField(blank=True, help_text='Внутреннее описание купона', max_length=200, verbose_name='Название')),
                ('discount_type', models.CharField(choices=[('percent', 'Процентная скидка'), ('fixed', 'Фиксированная сумма')], default='percent', help_text='percent - скидка в %, fixed - фиксированная сумма', max_length=10, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Процент (0-100) или сумма в рублях', max_digits=10, verbose_name='Размер скидки')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Минимальная сумма заказа для применения купона', max_digits=12, verbose_name='Минимальная сумма заказа')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Максимальная скидка (для процентных купонов). 0 - без ограничения', max_digits=12, null=True, verbose_name='Максимальная сумма скидки')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='Максимальное количество использований. 0 - без ограничений', verbose_name='Лимит использования')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество использований')),
                ('per_user_limit', models.PositiveIntegerField(default=0, help_text='Максимум использований одним пользователем. 0 - без ограничений', verbose_name='Лимит на пользователя')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('valid_from', models.DateTimeField(help_text='Дата и время начала действия', verbose_name='Действителен с')),
                ('valid_to', models.DateTimeField(help_text='Дата и время окончания действия', verbose_name='Действителен по')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Оставьте пустым для применения ко всем товарам', related_name='coupons', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
                'ordering': ['-created_at'],
            },
        ),
    ]
