# Generated by Django 5.2.1 on 2026-06-09 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +7 (999) 123-45-67', max_length=18, validators=[django.core.validators.RegexValidator(message='Введите номер в формате +7XXXXXXXXXX (11 цифр).', regex='^[78]\\d{10}$')], verbose_name='phone number'),
        ),
    ]
