# Generated by Django 5.2.1 on 2026-05-11 21:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_filterable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO ключевые слова')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание бренда')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, help_text='Если пусто, используется название', max_length=255, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, help_text='Если пусто, используется краткое описание', null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO ключевые слова')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул MegaMart')),
                ('supplier_sku', models.CharField(blank=True, max_length=64, null=True, verbose_name='Артикул поставщика')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, max_length=12, verbose_name='Цена (руб.)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание (HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Популярный товар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO ключевые слова')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Файл изображения')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный текст')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attribute', verbose_name='Характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
